- Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5960597603622396663">Bundle Update as a Service - Tachikoma.io</a>
> Exec tachikoma update 20150113024704

- Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5978354908222965078">Bundle Update as a Service - Tachikoma.io</a>
> Exec tachikoma update 20150303024814

- Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6011331458625154087">Bundle Update as a Service - Tachikoma.io</a>
> Exec tachikoma update 20150602024517

- Gemfile.lock
- adhoq.gemspec
- app/controllers/adhoq/explains_controller.rb
- app/views/adhoq/explains/create.html.slim
- app/views/adhoq/explains/statement_invalid.html.slim
- app/views/adhoq/queries/_form.html.slim
- config/routes.rb
- lib/adhoq/executor.rb
- spec/features/execute_adhoc_query_spec.rb
Because I want to see explain result of editing query, I implemented it.
If it looks good, Please merge this.
> [Feature Request] Enable explain editing query

- Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6013868171766553105">Bundle Update as a Service - Tachikoma.io</a>
> Exec tachikoma update 20150609024518

- Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6039730950656785783">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6039730950656785783">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20150819113458

- Gemfile.lock
- adhoq.gemspec
- app/decorators/adhoq/execution_decorator.rb
- app/models/adhoq/execution.rb
- app/views/adhoq/queries/_execution.html.slim
- app/views/adhoq/queries/_query.html.slim
- lib/adhoq/engine.rb
> Add active_decorator for status label

- Gemfile.lock
- adhoq.gemspec
- app/decorators/adhoq/query_decorator.rb
- app/views/adhoq/queries/_query.html.slim
cf. https://github.com/esminc/adhoq/pull/56
> highlighten SQL by rouge

- Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6044804365763700501">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6044804365763700501">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20150902113459

- README.md
it seems already supported .json(#11) and .csv(#10)
> Update README Future plannning section

- app/helpers/adhoq/application_helper.rb
- app/views/adhoq/current_tables/index.html.slim
- spec/dummy/app/models/no_id_table.rb
- spec/dummy/db/migrate/20150908112456_create_no_id_tables.rb
- spec/dummy/db/schema.rb
fix raise Unkown column error, if table has no id.
> support table has no id

- Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6047341073905481869">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6047341073905481869">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20150909113455

- spec/features/execute_adhoc_query_spec.rb
- spec/support/activejob_helper.rb
> Refactor active job test case

- Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6052414484959364957">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6052414484959364957">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20150923113452

- Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6060024676937464184">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6060024676937464184">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20151014113520

- spec/dummy/app/models/secret_table.rb
- spec/dummy/db/migrate/20150908073801_create_secret_tables.rb
> add test case for ignore table config

- Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6067634817598989151">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6067634817598989151">2015-06-28 Updated permissions - Tachikoma.io</a>
> Exec tachikoma update 20151104113447

- .travis.yml
- gemfiles/Gemfile-rails-edge
I add test config for edge Rails and recent Ruby version.
> Add test config for edge Rails and recent Ruby version

- app/controllers/adhoq/current_tables_controller.rb
Model classes inherits ApplicationRecord in Rails5.
> fix current_tables in rails5

- ChangeLog
- lib/adhoq/version.rb
> version up 0.1.1

- spec/support/codeclimate_reporter.rb
Code Climate Test Reporter is deprecated
> remove CodeClimate::TestReporter setting

- .travis.yml
> Use ruby 2 4 0

- app/helpers/adhoq/application_helper.rb
Follow up to rails/rails#28293.
> Use `ActiveRecord::SchemaMigration.table_name`

- lib/adhoq/version.rb
> bump version

- .gitignore
- gemfiles/Gemfile-rails-edge
Gemfile for Rail edge is broken dependency.
> Fix gemfile for Rails edge

- spec/models/adhoq/execution_spec.rb
> fix status spec on Ruby2.3

- .travis.yml
- adhoq.gemspec
This PR is based on #167.
Anothor approach to fix CI failure of #169
> fix rails4.x CI failure

- ChangeLog
- lib/adhoq/version.rb
> bump v0.5.0

- .travis.yml
- gemfiles/Gemfile-rails-6.0.x
Rails 6 will release next month. So I'd like to test with Rails6.
https://weblog.rubyonrails.org/2018/12/20/timeline-for-the-release-of-Rails-6-0/
> added Rails 6.0.0.beta3 to test matrix

- app/views/adhoq/queries/_form.html.erb
Once in a while, I may not want to enter description.
If you think description is needed, Please feel free to close this.
> I may not want to enter description

- .travis.yml
- gemfiles/Gemfile-rails-6.0.x
> update Rails version in Gemfile.6.0.x

- .travis.yml
> fix up exclude matrix

- adhoq.gemspec
axslx dosen't update long time.
> replace axslx to caxslx

- .travis.yml
Added Ruby 2.7.0 to build matrix.
> Add Ruby 2.7.2 and update Ruby versions in travis.yml
