esminc/adhoq

.travis.yml
app/views/adhoq/current_tables/index.html.slim
gemfiles/Gemfile-rails-4.2.x

`column` on Rails-4.2 does not have `primary` method.

[Bugfix] Fix current_tables view for Rails-4.2

---

app/controllers/adhoq/executions_controller.rb
app/models/adhoq/report.rb
app/views/adhoq/queries/_query.html.slim
lib/adhoq/global_variable.rb
lib/adhoq/storage.rb
lib/adhoq/storage/on_the_fly.rb
spec/adhoq/storage_spec.rb
spec/models/adhoq/execution_spec.rb

On the fly storage enables
- direct execution -> report download
- work without local directory and S3 bucket
disables
- re-download of an report
Easy to setup and start using

On the fly storage

---

app/helpers/adhoq/application_helper.rb
gemfiles/Gemfile-rails-3.2.x
lib/adhoq.rb
lib/adhoq/configuration.rb
lib/adhoq/executor.rb
lib/adhoq/executor/connection_wrapper.rb
spec/adhoq/executor/connection_wrapper_spec.rb
spec/adhoq/executor_spec.rb

I want to execute query on different database from `ActiveRecord::Base.connection`.
I propose `Adhoq.config.database_connection`.
Even if database for analyzing is different from production database, We will be able to use `adhoq`
for example
```ruby
Adhoq.configuration do |c|
c.database_connection = -> { OtherDatabaseModel.connection }
end
```

[Feature Request] Make changeable query execution target

---

app/controllers/adhoq/executions_controller.rb
app/models/adhoq/report.rb
lib/adhoq/storage/fog_storage.rb
lib/adhoq/storage/on_the_fly.rb
lib/adhoq/storage/s3.rb

If report data is huge, server process consumes much memory and takes a lot of time to download from S3.
This patch allows client user to download directly from S3, via pre-signed url.
pre-signed url is available only for 1 minite.

[Feature Request] Implement direct download from S3

---

app/models/adhoq/report.rb
lib/adhoq/storage/fog_storage.rb
lib/adhoq/storage/s3.rb

This patch fixes response-content-disposition, because previous format cannot use UTF-8 filename.
And, refactor responsibility of parameter options.

Fix direct s3 download multibyte filename

---

app/controllers/adhoq/executions_controller.rb
app/jobs/adhoq/execute_job.rb
lib/adhoq/configuration.rb
spec/features/execute_adhoc_query_spec.rb

I often want to execute a long time query.
But current adhoq execution is synchronous, and so HTTP timeout error is occured by long time query.
If adhoq with Rails-4.2.x or later, this patch enable async execution feature.

[Feature] Implement async query execution feature by activejob

---

app/controllers/adhoq/current_tables_controller.rb
lib/adhoq/configuration.rb
spec/dummy/config/environments/test.rb
spec/dummy/config/initializers/adhoq.rb
spec/dummy/db/schema.rb
spec/features/show_database_schema_spec.rb

I have prepared the settings that you can specify the table name that
you do not want to appear in the table list.
For example,
```
config.ignore_table_names = %w(SecretTable)
```
The specified table will not appear in the table list.

add igonre table config for show#tables

---

README.md
lib/adhoq/configuration.rb

What do you think is to provide a default storage?

use :on_the_fly, if unset :storage configuration

---

adhoq.gemspec

I intended to drop support for 3.2, but dependecy wasn't.

update Rails version dependency

---

app/helpers/adhoq/application_helper.rb

SchemaMigration was introduced since 4.0.
Now, Adhoq support version over Rails4.0.
So, it is unnecessary check.
And, I think schema_version should check from Adhoq::ConnectionWrapper.

remove case dividing by ActiveRecord::SchemaMigration

---

gemfiles/Gemfile-rails-4.0.x
gemfiles/Gemfile-rails-4.1.x
gemfiles/Gemfile-rails-4.2.x

This PR solved the following dependencies.
- fog-core 1.44 depends xmlrpc, requires Ruby version >= 2.3.0
- nio4r 2 depends xmlrpc, requires Ruby version >= 2.2.2
- Rack 2 requires Ruby version >= 2.2.2
Refer: https://travis-ci.org/esminc/adhoq/builds/227115534

Fix build error on Travis CI

---

adhoq.gemspec
lib/adhoq/storage/local_file.rb
lib/adhoq/storage/s3.rb

I've got following message when I add `gem 'adhoq'` to the Gemfile and run `bundle install`.
```
Post-install message from fog:
------------------------------
Thank you for installing fog!
IMPORTANT NOTICE:
If there's a metagem available for your cloud provider, e.g. `fog-aws`,
you should be using it instead of requiring the full fog collection to avoid
unnecessary dependencies.
'fog' should be required explicitly only if:
- The provider you use doesn't yet have a metagem available.
- You require Ruby 1.9.3 support.
------------------------------
```
Notice: I'm not testing in production yet 🙈

Use metagem fog-aws/fog-local to reduce unnecessary dependencies

---

app/controllers/adhoq/application_controller.rb
lib/adhoq/configuration.rb
spec/dummy/app/controllers/my_application_controller.rb
spec/dummy/config/initializers/adhoq.rb

Adhoq requires a controller which inherit ActionController::Base.
But in some environment the ApplicationController inherited ActionController::API.
Configurable base_controller helps that situation.

Add base_controller configuration

---

app/controllers/adhoq/current_tables_controller.rb
spec/dummy/app/models/abstract_table.rb

Adhoq reject `abstract_class` based on name which is `ApplicationRecord`, but I have another `abstract_class` `Admin::ApplicationRecord` like following:
```rb
module Admin
class ApplicationRecord < ActiveRecord::Base
self.abstract_class = true
end
end
```
It can be hidden by `config.hidden_model_names`, but it is not convenient.
I added a `abstract_class?` filter for `@ar_classes` setup.

Hide model if model is abstract_class

---

config/routes.rb

Because, Rails API mode doesn't define edit and new.
ref https://github.com/esminc/adhoq/issues/122

specify routes

---

app/views/adhoq/explains/statement_invalid.html.slim
app/views/adhoq/previews/statement_invalid.html.slim
spec/features/execute_adhoc_query_spec.rb

Rails 5.1 removed `original_exception` method from ActiveRecord::StatementInvalid so we need to use `cause` method instead.
https://github.com/rails/rails/commit/bc6c5df4699d3f6b4a61dd12328f9e0f1bd6cf46

Fix ActionView::Template::Error on SQL statement error

---

app/controllers/adhoq/current_tables_controller.rb

If there is an anonymous class inherited ActiveRecord::Base(e.g. SwitchPoint), the show table feature fails.
Because the name is nil in anonymous classes, it fails sorting by table name.
So I excluded anonymous classes.

Fix show table feature error(a case where there is an anonymous class  inherited ActiveRecord::Base)

---

adhoq.gemspec
spec/factories/adhoq_queries.rb
spec/spec_helper.rb

FactoryGirl has been renamed as FactoryBot.
Ref: https://robots.thoughtbot.com/factory_bot
This commit fixes the following warning message:
```
DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot.
See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions.
```

Migrate from FactoryGirl to FactoryBot

---

adhoq.gemspec

For upgrading [axlsx](https://github.com/randym/axlsx) gem version of github repository, 
dependency error raise as bundle install.
```
Bundler could not find compatible versions for gem "axlsx":
In Gemfile:
axlsx
adhoq was resolved to 0.2.0, which depends on
axlsx (~> 2.0)
...
```

Change the dependency condition of axlsx for upgrading axlsx github repository(not rubygems) to version 3

---

adhoq.gemspec

For upgrading axlsx gem version of github repository, dependency error raise as bundle install.
```
Bundler could not find compatible versions for gem "fog-aws":
In snapshot (Gemfile.lock):
fog-aws (= 2.0.0)
In Gemfile:
adhoq was resolved to 0.2.0, which depends on
fog-aws (~> 1.4)
```

Change the dependency condition of fog-aws

---

.travis.yml
gemfiles/Gemfile-rails-5.2.x

ruby 2.2 is EOL https://www.ruby-lang.org/ja/news/2017/12/14/ruby-2-2-9-released/
And current test matrix failed by this. 
https://travis-ci.org/esminc/adhoq/jobs/413525036
```
Gem::RuntimeRequirementNotMetError: byebug requires Ruby version >= 2.2.0. The
current ruby version is 2.1.0.
An error occurred while installing byebug (10.0.2), and Bundler
```
and Rails 5.2 is already released https://weblog.rubyonrails.org/2018/8/7/Rails-5-2-1-has-been-released/

drop support below ruby 2.3 and test with Rails 5.2

---

app/views/adhoq/current_tables/index.html.slim
lib/adhoq/configuration.rb

current_tables page  execute count query for each all tables.
It's too heavy for some service. So I'd like to disable this feature.

allow to hide rows count

---

app/views/adhoq/queries/_query.html.slim

`Adhoq::QueriesController#show` execute N+1 queries.
BEFORE
```
Started GET "/adhoq/q/3" for 127.0.0.1 at 2018-08-08 20:07:04 +0900
Processing by Adhoq::QueriesController#show as HTML
Parameters: {"id"=>"3"}
(0.3ms)  SET NAMES utf8mb4 COLLATE utf8mb4_bin,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
Adhoq::Query Load (0.3ms)  SELECT  `adhoq_queries`.* FROM `adhoq_queries` WHERE `adhoq_queries`.`id` = 3 LIMIT 1
Adhoq::Execution Load (0.3ms)  SELECT `adhoq_executions`.* FROM `adhoq_executions` WHERE `adhoq_executions`.`query_id` = 3
Adhoq::Report Load (0.3ms)  SELECT `adhoq_reports`.* FROM `adhoq_reports` WHERE `adhoq_reports`.`execution_id` IN (4, 5, 6, 10, 13, 15) …
```

fix N+1 queries for adhoq_reports

---

lib/adhoq/executor/connection_wrapper.rb

Executorのattributeとしてconnectionを持ってしまうと、いつ開放されるかを外部から制御しにくいためconnectionを確保して実行するところまでを責務としてしまった方が拡張しやすくてよいと感じました。
背景としては、 http://walf443.hatenablog.com/entry/2018/08/08/230256 といった感じです。

ConnectionWrapperのSQL実行時にconnectionのscopeを限定する

---

lib/adhoq/global_variable.rb
lib/adhoq/storage.rb
lib/adhoq/storage/cache.rb

```
Adhoq.configure do |config|
config.storage = [:cache, Rails.cache, 'adhoq:']
end
```
OnTheFlyのように実行結果が一定期間経つと消えてよいが、複数のアプリケーションサーバーがあると結果を取得できるかわからないといった点がめんどうなので、Rails.cacheに保存できるAdhoq::Storage::Cache を書きました。

added cache storage

---

app/models/adhoq/execution.rb
spec/models/adhoq/execution_spec.rb

When query is invalid and it ran failure, it got error with ActiveRecord::NotNullViolation
```                                                                                                                                                                                                                                              Failures
1) Adhoq::Execution#generate_report! when execute query failed should change `execution.status` to "failure"
Failure/Error: update_attributes(status: :failure)
ActiveRecord::NotNullViolation:
SQLite3::ConstraintException: NOT NULL constraint failed: adhoq_reports.identifier: INSERT INTO "adhoq_reports" ("execution_id", "created_at", "updated_at") VALUES (?, ?, ?) 
```

Fix exexution failure handling

---

adhoq.gemspec

It got some errors on tests except using Gemfile-rails-edge followings:
```
Gem::LoadError: can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile.
```
https://travis-ci.org/esminc/adhoq/jobs/511830967 on https://github.com/esminc/adhoq/pull/166
It seems that sqlite3 gem v1.4.0 released with breaking changes.
see also https://qiita.com/Kta-M/items/254a1ba141827a989cb7

fixed sqlite3 activation error.

---

adhoq.gemspec
spec/factories/adhoq_queries.rb

This fix is based on #167 
This fixed to unlock factory_bot gem's version.
These error cased by depcatation of static attributes
https://github.com/thoughtbot/factory_bot/releases/tag/v5.0.0 
> Removed: static attributes (use dynamic attributes with a block instead)

support FactoryBot v5

---

gemfiles/Gemfile-rails-5.1.x
gemfiles/Gemfile-rails-5.2.x
gemfiles/Gemfile-rails-edge
lib/adhoq/engine.rb

This PR is regression of #166.
I'm sorry for that.
```
$ cd spec/dummy
$ bundle exec rails server
```
and go http://localhost:3000/adhoq/
I got
```
LoadError (cannot load such file -- sass):
activesupport (5.2.3) lib/active_support/dependencies.rb:291:in `require'
activesupport (5.2.3) lib/active_support/dependencies.rb:291:in `block in require'
activesupport (5.2.3) lib/active_support/dependencies.rb:257:in `load_dependency'
activesupport (5.2.3) lib/active_support/dependencies.rb:291:in `require'
sprockets (3.7.2) lib/sprockets/autoload/sass.rb:1:in `<top (required)>'
activesupport (5.2.3) lib/active_support/dependencies.rb:291:in `require'
activesupport (5.2.3) lib/active_support/dependencies.rb:291:in `block in require'
activesupport (5.2.3) lib/active_support/dependencies.rb:257:in …
```

fix sass loading error

---

app/models/adhoq/time_based_orders.rb

This PR fix following warnings:
```
DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "\"adhoq_queries\".updated_at DESC". Non-attribute arguments will be disallowed in Rails 6.0.
This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from block (2 levels) in <module:TimeBasedOrders> at /User
s/yoshimin/src/github.com/esminc/adhoq/app/models/adhoq/time_based_orders.rb:6)
```
This behaviour introduced since Rails 5.2.0.
https://github.com/rails/rails/blob/5-2-stable/activerecord/CHANGELOG.md
> Require raw SQL fragments to be explicitly marked when used in relation query methods.
> Before:
> …

fix Dangerous query method warnings

---

spec/dummy/config/environments/test.rb

This PR fix following warnings:
```
DEPRECATION WARNING: Leaving `ActiveRecord::ConnectionAdapters::SQLite3Adapter.represent_boolean_as_integer`
set to false is deprecated. SQLite databases have used 't' and 'f' to serialize
boolean values and must have old data converted to 1 and 0 (its native boolean
serialization) before setting this flag to true. Conversion can be accomplished
by setting up a rake task which runs
ExampleModel.where("boolean_column = 't'").update_all(boolean_column: 1)
ExampleModel.where("boolean_column = 'f'").update_all(boolean_column: 0)
for all models and all boolean columns, after which the flag must be set to
true by adding the following to your application.rb file:
Rails.application.config.active_record.sqlite3.represent_boolean_as_integer = true
(called from …
```

fix sqlite type conversion warnings

---

.gitignore

On my enviroment, Gemfile.lock is not ignored.
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
Gemfile.lock
nothing added to commit but untracked files present (use "git add" to track)
```
```
$ git --version
git version 2.20.1 (Apple Git-117)
```
It seems that ./ is not working on .gitignore
https://git-scm.com/docs/gitignore

ignore Gemfile.lock

---

adhoq.gemspec
app/controllers/adhoq/queries_controller.rb
app/models/adhoq/execution.rb
gemfiles/Gemfile-rails-6.0.x
spec/dummy/config/environments/test.rb

Rails6.0.0rc1 was released.
https://weblog.rubyonrails.org/2019/4/24/Rails-6-0-rc1-released/

adopt Rails6.0.0 rc1

---

.travis.yml

#169 remove Rails5.1 environement, but other changes introduced again.

Remove old test matrix settings

---

spec/dummy/app/assets/config/manifest.js

```
ActionView::Template::Error:
Asset `adhoq/application.js` was not declared to be precompiled in production.
Declare links to your assets in `app/assets/config/manifest.js`.
//= link adhoq/application.js
and restart your server
```

fix assets errors in spec

---

.travis.yml

over Rails6 can't install Ruby2.4

exclude matrix rails-edge with 2.4

---

.travis.yml

fix the following errors
```
bundler's executable "bundle" conflicts with /home/travis/.rvm/rubies/ruby-2.4.9/bin/bundle
Overwrite the executable? [yN]  
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

remove gem upate system and stop install bundler

---

app/helpers/adhoq/application_helper.rb

lang: EN
The table `ar_internal_metadata` added in Rails5 has a`key` column as a PRIMARY KEY, and since `KEY` is a reserved word in MySQL 8.0, a SQL Syntax error occurs when the return value of table_order_key is a String.
Fixed to return Symbol so that column names are enclosed in quotes.
lang: JA
Rails5で追加されたテーブル `ar_internal_metadata` は `key` カラムを PRIMARY KEYとして持ち、且つMySQL8.0で`KEY`が予約語となったためtable_order_keyの返り値がStringの場合にSQL Syntaxエラーとなる。
カラム名がクォートで囲まれるようにするためSymbolを返すよう修正した。
String
```
SELECT `ar_internal_metadata`.* FROM `ar_internal_metadata` ORDER BY key LIMIT 1
```
Symbol
```
SELECT `ar_internal_metadata`.* FROM `ar_internal_metadata` ORDER BY `ar_internal_metadata`.`key` ASC LIMIT 1
```

Symbolize table_order_key in ApplicationHelper

---

adhoq.gemspec

Since Ruby 3.4, csv is no longer a “default gem” although it is included as a standard library, so I added it to the gemspec.
https://docs.ruby-lang.org/en/3.4/standard_library_md.html

Add csv to gemspec
